export const AI_STRINGS = {
  ko: {
    tabGreetings: {
      vent: '지금 어떤 감정인지 말해줄래요?',
      dig:  '패턴을 더 깊이 들여다볼까요?',
      get:  '당신에 대해 더 알아보고 싶어요.',
      set:  '오늘 어떤 선택을 해볼까요?',
      me:   '변화를 함께 돌아볼까요?',
    } as Record<string, string>,
    defaultGreeting: '무엇이든 말해줄래요?',
    sttErrors: {
      'no-speech':   { tts: '아무 말씀도 안 들렸어요. 다시 말씀해주시거나 화면 아래 텍스트 입력을 사용해주세요.', aria: '음성이 감지되지 않았어요. 다시 시도하거나 텍스트로 입력해주세요.' },
      'not-allowed': { tts: '마이크 접근이 거부되었어요. 화면 아래 텍스트 입력을 사용해주세요.', aria: '마이크 권한이 거부되었어요. 텍스트로 입력해주세요.' },
      'network':     { tts: '네트워크 연결을 확인해주세요.', aria: '네트워크 오류가 발생했어요.' },
    } as Record<string, { tts: string; aria: string }>,
    statusListening: '듣고 있어요. 말씀해주세요.',
    statusThinking: (name: string) => `${name}가 생각하고 있어요.`,
    statusStopped: '음성 입력이 중지되었어요.',
    statusReadStopped: '읽기가 중지되었어요.',
    fallbackText: '연결이 불안정해요. 다시 말해줄래요?',
    connError: '연결 오류가 발생했어요. 다시 시도해주세요.',
    sttGenericError: '음성 인식 중 오류가 발생했어요.',
    swipeHint: '아래로 스와이프하면 돌아가요',
    dialogLabel: (name: string) => `${name} 음성 대화 — 음성 또는 텍스트로 대화할 수 있어요`,
    chatLogLabel: '대화 기록',
    inputLabel: 'AI에게 보낼 메시지를 입력해요. 음성 대신 텍스트로도 대화할 수 있어요.',
    inputPlaceholderThinking: (name: string) => `${name}가 생각하고 있어요...`,
    inputPlaceholderListening: '말하거나 직접 입력해도 돼요...',
    inputPlaceholderIdle: '또는 여기에 적어요...',
    sendLabel: '메시지 전송',
    micLabelListening: '음성 입력 중지',
    micLabelThinking: '응답 대기 중, 잠시 기다려주세요',
    micLabelStart: '음성 입력 시작',
    micLabelUnsupported: '음성 인식을 지원하지 않는 브라우저입니다',
    stopReadLabel: '읽기 중지',
    closeLabel: '대화 모드 닫기',
    sttUnsupported: '이 브라우저는 음성 인식을 지원하지 않아요. 텍스트로 대화해주세요.',
    speakerMe: '나:',
  },
  en: {
    tabGreetings: {
      vent: 'How are you feeling right now?',
      dig:  'Shall we look deeper into the patterns?',
      get:  "I'd like to learn more about you.",
      set:  "What choices shall we explore today?",
      me:   "Let's reflect on your changes together.",
    } as Record<string, string>,
    defaultGreeting: 'Tell me anything.',
    sttErrors: {
      'no-speech':   { tts: "I didn't hear anything. Please try again or use the text input below.", aria: "No speech detected. Please try again or type instead." },
      'not-allowed': { tts: 'Microphone access was denied. Please use the text input below.', aria: 'Microphone permission denied. Please type instead.' },
      'network':     { tts: 'Please check your network connection.', aria: 'A network error occurred.' },
    } as Record<string, { tts: string; aria: string }>,
    statusListening: "Listening. Go ahead.",
    statusThinking: (name: string) => `${name} is thinking.`,
    statusStopped: 'Voice input stopped.',
    statusReadStopped: 'Reading stopped.',
    fallbackText: "Connection is unstable. Could you say that again?",
    connError: 'A connection error occurred. Please try again.',
    sttGenericError: 'A speech recognition error occurred.',
    swipeHint: 'Swipe down to go back',
    dialogLabel: (name: string) => `${name} voice chat — you can talk by voice or text`,
    chatLogLabel: 'Conversation log',
    inputLabel: 'Type a message to the AI. You can also chat by text instead of voice.',
    inputPlaceholderThinking: (name: string) => `${name} is thinking...`,
    inputPlaceholderListening: 'Speak or type here...',
    inputPlaceholderIdle: 'Or type here...',
    sendLabel: 'Send message',
    micLabelListening: 'Stop voice input',
    micLabelThinking: 'Waiting for response, please wait',
    micLabelStart: 'Start voice input',
    micLabelUnsupported: 'This browser does not support speech recognition',
    stopReadLabel: 'Stop reading',
    closeLabel: 'Close voice chat',
    sttUnsupported: "This browser doesn't support speech recognition. Please chat by text.",
    speakerMe: 'Me:',
  },
};
