#!/usr/bin/env /opt/homebrew/bin/python3.11
"""
Step 2: 기존 100개 키워드 태그 배정
Step 3: 신규 키워드 400개 삽입
"""
import json, requests, sys, time

URL  = "https://qwiwotodwfgkpdasdhhl.supabase.co/rest/v1/codetalk_keywords"
KEY  = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3aXdvdG9kd2Zna3BkYXNkaGhsIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MDQ3NDYzNSwiZXhwIjoyMDg2MDUwNjM1fQ.ik0JCPcaht8lVgDiNyIaEvg7kPGvh19J1Ff6xjf9N0k"
HEADERS = {
    "apikey": KEY,
    "Authorization": f"Bearer {KEY}",
    "Content-Type": "application/json",
    "Accept-Profile": "veilor",
    "Content-Profile": "veilor",
    "Prefer": "return=minimal",
}

def sb_get_all():
    r = requests.get(URL + "?select=id,keyword&limit=1000", headers=HEADERS)
    r.raise_for_status()
    return r.json()

def sb_patch(kw_id, rel_tags, psych_tags):
    r = requests.patch(
        URL + f"?id=eq.{kw_id}",
        headers=HEADERS,
        json={"rel_tags": rel_tags, "psych_tags": psych_tags},
    )
    r.raise_for_status()

def sb_insert_batch(rows):
    r = requests.post(URL, headers=HEADERS, json=rows)
    if r.status_code not in (200, 201):
        print(f"  INSERT ERR {r.status_code}: {r.text[:200]}")
        r.raise_for_status()

# ──────────────────────────────────────────────────────────────
# Step 2: 기존 100개 키워드 태그 매핑
# ──────────────────────────────────────────────────────────────
EXISTING_TAGS = {
    # keyword: (rel_tags, psych_tags)
    "사랑":     (["rel_lover", "rel_self"],             ["psych_emotion", "psych_attachment"]),
    "행복":     (["rel_self"],                           ["psych_emotion", "psych_growth"]),
    "자유":     (["rel_self", "rel_society"],            ["psych_identity", "psych_boundary"]),
    "신뢰":     (["rel_lover", "rel_friend"],            ["psych_attachment", "psych_boundary"]),
    "존중":     (["rel_lover", "rel_friend", "rel_family"], ["psych_boundary", "psych_identity"]),
    "안전":     (["rel_self", "rel_lover"],              ["psych_attachment", "psych_emotion"]),
    "외로움":   (["rel_self"],                           ["psych_attachment", "psych_emotion"]),
    "연결":     (["rel_lover", "rel_friend", "rel_self"], ["psych_attachment", "psych_emotion"]),
    "경계":     (["rel_lover", "rel_family", "rel_self"], ["psych_boundary"]),
    "솔직함":   (["rel_lover", "rel_friend"],            ["psych_boundary", "psych_emotion"]),
    "배려":     (["rel_lover", "rel_family", "rel_friend"], ["psych_emotion", "psych_boundary"]),
    "기대":     (["rel_lover", "rel_family"],            ["psych_attachment", "psych_emotion"]),
    "실망":     (["rel_lover", "rel_family"],            ["psych_emotion", "psych_attachment"]),
    "용기":     (["rel_self"],                           ["psych_identity", "psych_growth"]),
    "취약함":   (["rel_self", "rel_lover"],              ["psych_attachment", "psych_emotion"]),
    "위로":     (["rel_lover", "rel_friend", "rel_family"], ["psych_emotion"]),
    "침묵":     (["rel_lover", "rel_family"],            ["psych_boundary", "psych_emotion"]),
    "시간":     (["rel_self", "rel_lover"],              ["psych_growth", "psych_attachment"]),
    "거리":     (["rel_lover", "rel_family"],            ["psych_attachment", "psych_boundary"]),
    "변화":     (["rel_self", "rel_lover"],              ["psych_growth", "psych_identity"]),
    "공감":     (["rel_lover", "rel_friend", "rel_family"], ["psych_emotion", "psych_boundary"]),
    "감사":     (["rel_lover", "rel_family", "rel_friend"], ["psych_emotion"]),
    "질투":     (["rel_lover"],                          ["psych_emotion", "psych_attachment"]),
    "자존감":   (["rel_self"],                           ["psych_identity"]),
    "의존":     (["rel_lover", "rel_family"],            ["psych_attachment"]),
    "자립":     (["rel_self"],                           ["psych_identity", "psych_growth"]),
    "선택":     (["rel_self", "rel_lover"],              ["psych_identity", "psych_boundary"]),
    "용서":     (["rel_lover", "rel_family"],            ["psych_emotion", "psych_trauma"]),
    "이별":     (["rel_lover"],                          ["psych_emotion", "psych_attachment"]),
    "나":       (["rel_self"],                           ["psych_identity"]),
    "소통":     (["rel_lover", "rel_friend", "rel_family"], ["psych_boundary"]),
    "싸움":     (["rel_lover", "rel_family"],            ["psych_boundary", "psych_emotion"]),
    "화해":     (["rel_lover", "rel_family"],            ["psych_emotion", "psych_boundary"]),
    "헌신":     (["rel_lover", "rel_family"],            ["psych_attachment", "psych_desire"]),
    "소유":     (["rel_lover"],                          ["psych_attachment", "psych_boundary"]),
    "독점":     (["rel_lover"],                          ["psych_attachment", "psych_boundary"]),
    "비밀":     (["rel_lover", "rel_family"],            ["psych_boundary", "psych_trauma"]),
    "거짓말":   (["rel_lover", "rel_friend"],            ["psych_boundary", "psych_trauma"]),
    "권력":     (["rel_lover", "rel_family", "rel_society"], ["psych_boundary", "psych_identity"]),
    "평등":     (["rel_lover", "rel_society"],           ["psych_boundary", "psych_identity"]),
    "역할":     (["rel_lover", "rel_family", "rel_society"], ["psych_identity", "psych_boundary"]),
    "책임":     (["rel_lover", "rel_family"],            ["psych_boundary", "psych_identity"]),
    "약속":     (["rel_lover", "rel_friend"],            ["psych_attachment", "psych_boundary"]),
    "욕구":     (["rel_self", "rel_lover"],              ["psych_desire"]),
    "섹스":     (["rel_lover"],                          ["psych_sexuality", "psych_desire"]),
    "친밀감":   (["rel_lover"],                          ["psych_desire", "psych_attachment"]),
    "거부":     (["rel_lover", "rel_family"],            ["psych_boundary", "psych_emotion"]),
    "집착":     (["rel_lover"],                          ["psych_attachment", "psych_trauma"]),
    "이기심":   (["rel_self", "rel_lover"],              ["psych_identity", "psych_boundary"]),
    "희생":     (["rel_lover", "rel_family"],            ["psych_attachment", "psych_emotion"]),
    "성장":     (["rel_self"],                           ["psych_growth", "psych_identity"]),
    "습관":     (["rel_self", "rel_lover"],              ["psych_trauma", "psych_growth"]),
    "설렘":     (["rel_lover"],                          ["psych_emotion", "psych_desire"]),
    "안도":     (["rel_self", "rel_lover"],              ["psych_emotion", "psych_attachment"]),
    "피로":     (["rel_self", "rel_lover"],              ["psych_emotion", "psych_boundary"]),
    "관심":     (["rel_lover", "rel_family"],            ["psych_attachment", "psych_desire"]),
    "인정":     (["rel_self", "rel_lover", "rel_family"], ["psych_identity", "psych_emotion"]),
    "갈등":     (["rel_lover", "rel_family"],            ["psych_boundary", "psych_emotion"]),
    "타협":     (["rel_lover", "rel_family"],            ["psych_boundary", "psych_growth"]),
    "우리":     (["rel_lover"],                          ["psych_attachment", "psych_identity"]),
    "돈":       (["rel_lover", "rel_family", "rel_society"], ["psych_boundary", "psych_identity"]),
    "계층":     (["rel_society"],                        ["psych_identity", "psych_boundary"]),
    "결혼":     (["rel_lover", "rel_family"],            ["psych_attachment", "psych_identity"]),
    "이혼":     (["rel_lover", "rel_family"],            ["psych_trauma", "psych_emotion"]),
    "부모":     (["rel_family"],                         ["psych_attachment", "psych_trauma"]),
    "자녀":     (["rel_family"],                         ["psych_attachment", "psych_desire"]),
    "외도":     (["rel_lover"],                          ["psych_trauma", "psych_boundary"]),
    "폭력":     (["rel_lover", "rel_family"],            ["psych_trauma", "psych_boundary"]),
    "트라우마": (["rel_self", "rel_family"],             ["psych_trauma"]),
    "치유":     (["rel_self"],                           ["psych_trauma", "psych_growth"]),
    "중독":     (["rel_self"],                           ["psych_trauma", "psych_attachment"]),
    "통제":     (["rel_lover", "rel_family"],            ["psych_boundary", "psych_trauma"]),
    "수치심":   (["rel_self"],                           ["psych_emotion", "psych_trauma"]),
    "죄책감":   (["rel_self", "rel_lover"],              ["psych_emotion", "psych_trauma"]),
    "분노":     (["rel_self", "rel_lover"],              ["psych_emotion", "psych_trauma"]),
    "성정체성": (["rel_self", "rel_society"],            ["psych_identity", "psych_sexuality"]),
    "욕망":     (["rel_self", "rel_lover"],              ["psych_desire", "psych_sexuality"]),
    "동의":     (["rel_lover"],                          ["psych_boundary", "psych_sexuality"]),
    "나이":     (["rel_self", "rel_society"],            ["psych_identity", "psych_attachment"]),
    "죽음":     (["rel_self", "rel_family"],             ["psych_emotion", "psych_trauma"]),
    "고독":     (["rel_self"],                           ["psych_attachment", "psych_identity"]),
    "독신":     (["rel_self", "rel_society"],            ["psych_identity", "psych_desire"]),
    "폴리아모리": (["rel_lover"],                        ["psych_attachment", "psych_sexuality"]),
    "퀴어":     (["rel_self", "rel_society"],            ["psych_identity", "psych_sexuality"]),
    "종교":     (["rel_self", "rel_society"],            ["psych_identity", "psych_boundary"]),
    "문화":     (["rel_self", "rel_society"],            ["psych_identity", "psych_boundary"]),
    "젠더":     (["rel_self", "rel_society"],            ["psych_identity", "psych_sexuality"]),
    "AI":       (["rel_self", "rel_society"],            ["psych_identity", "psych_boundary"]),
    "SNS":      (["rel_self", "rel_society"],            ["psych_attachment", "psych_identity"]),
    "장거리":   (["rel_lover"],                          ["psych_attachment", "psych_emotion"]),
    "재결합":   (["rel_lover"],                          ["psych_attachment", "psych_trauma"]),
    "전 연인":  (["rel_lover"],                          ["psych_attachment", "psych_trauma"]),
    "비교":     (["rel_self", "rel_lover"],              ["psych_identity", "psych_emotion"]),
    "완벽함":   (["rel_self"],                           ["psych_identity", "psych_trauma"]),
    "포기":     (["rel_self", "rel_lover"],              ["psych_emotion", "psych_growth"]),
    "새로 시작": (["rel_self", "rel_lover"],             ["psych_growth", "psych_identity"]),
    "감사함":   (["rel_self", "rel_lover", "rel_family"], ["psych_emotion", "psych_growth"]),
    "후회":     (["rel_self", "rel_lover"],              ["psych_emotion", "psych_trauma"]),
    "의미":     (["rel_self"],                           ["psych_identity", "psych_growth"]),
    "합의":     (["rel_lover"],                          ["psych_boundary", "psych_sexuality"]),
}

# ──────────────────────────────────────────────────────────────
# Step 3: 신규 키워드 400개
# ──────────────────────────────────────────────────────────────
NEW_KEYWORDS = [
    # ── psych_attachment (50개) ──────────────────────────────
    {"keyword": "애착", "description": "나는 어떤 방식으로 사람에게 붙어 있으려 하는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_attachment"]},
    {"keyword": "분리", "description": "떨어짐을 나는 어떻게 견디는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_attachment"]},
    {"keyword": "불안", "description": "관계 안에서 나를 불안하게 만드는 것은 무엇인가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_attachment", "psych_emotion"]},
    {"keyword": "회피", "description": "나는 친밀감을 피할 때 어떤 모습인가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_attachment"]},
    {"keyword": "매달림", "description": "나는 언제 상대를 놓지 못하는가", "rel_tags": ["rel_lover"], "psych_tags": ["psych_attachment"]},
    {"keyword": "떠남", "description": "누군가 먼저 떠났을 때 내 안에 남는 것은", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_attachment", "psych_emotion"]},
    {"keyword": "기다림", "description": "나는 무엇을 기다리며 관계를 유지하는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_attachment"]},
    {"keyword": "재확인", "description": "나는 얼마나 자주 상대의 마음을 확인하려 하는가", "rel_tags": ["rel_lover"], "psych_tags": ["psych_attachment"]},
    {"keyword": "융합", "description": "나와 상대의 경계가 흐릿해질 때 어떤 감각인가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_attachment", "psych_boundary"]},
    {"keyword": "안정감", "description": "나에게 안정감을 주는 관계는 어떤 모습인가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_attachment"]},
    {"keyword": "버림받음", "description": "버림받는 것에 대한 두려움이 내 행동을 어떻게 바꾸는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_attachment", "psych_trauma"]},
    {"keyword": "밀착", "description": "나는 가까움을 어느 정도까지 허용하는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_attachment"]},
    {"keyword": "거리두기", "description": "나는 언제 의도적으로 멀어지려 하는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_attachment", "psych_boundary"]},
    {"keyword": "그리움", "description": "나는 무엇을 그리워하는가, 그 사람인가 그 감각인가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_attachment", "psych_emotion"]},
    {"keyword": "매력", "description": "나는 어떤 사람에게 끌리고 왜 끌리는가", "rel_tags": ["rel_lover"], "psych_tags": ["psych_attachment", "psych_desire"]},
    {"keyword": "보호본능", "description": "나는 누구를 지키고 싶을 때 어떤 감정을 느끼는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_attachment"]},
    {"keyword": "미련", "description": "관계가 끝난 후에도 남는 그것은 무엇인가", "rel_tags": ["rel_lover"], "psych_tags": ["psych_attachment", "psych_emotion"]},
    {"keyword": "집에 있는 느낌", "description": "어떤 사람 곁에서 비로소 편안해지는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_attachment"]},
    {"keyword": "연락", "description": "연락의 빈도와 속도로 나는 무엇을 측정하는가", "rel_tags": ["rel_lover", "rel_friend"], "psych_tags": ["psych_attachment"]},
    {"keyword": "온기", "description": "내가 느끼는 관계의 온기는 어디에서 오는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_attachment", "psych_emotion"]},
    {"keyword": "품어줌", "description": "나는 누군가를 품어준 경험이 있는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_attachment"]},
    {"keyword": "돌봄", "description": "나는 돌봄을 받을 때 어떤 반응이 일어나는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_attachment"]},
    {"keyword": "공생", "description": "두 사람이 서로에게 의지할 때 그 구조는 건강한가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_attachment", "psych_boundary"]},
    {"keyword": "혼자됨", "description": "혼자인 것이 두려운가, 아니면 선택인가", "rel_tags": ["rel_self"], "psych_tags": ["psych_attachment", "psych_identity"]},
    {"keyword": "접촉", "description": "신체적 접촉이 나에게 어떤 의미를 가지는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_attachment", "psych_sexuality"]},
    {"keyword": "낯섦", "description": "친밀한 사람에게도 낯섦을 느낀 적 있는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_attachment", "psych_emotion"]},
    {"keyword": "순간이탈", "description": "대화 중 갑자기 멀어지는 내 감각은 무엇인가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_attachment", "psych_trauma"]},
    {"keyword": "위탁", "description": "나는 누군가에게 내 감정을 맡겨두고 있는가", "rel_tags": ["rel_lover"], "psych_tags": ["psych_attachment"]},
    {"keyword": "아이처럼", "description": "관계에서 나는 언제 어린아이처럼 되는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_attachment", "psych_trauma"]},
    {"keyword": "실마리", "description": "나는 무엇을 붙잡고 관계를 이어가는가", "rel_tags": ["rel_lover"], "psych_tags": ["psych_attachment"]},
    {"keyword": "믿음", "description": "나는 어떻게 신뢰를 형성하고 어떻게 잃는가", "rel_tags": ["rel_lover", "rel_friend"], "psych_tags": ["psych_attachment", "psych_boundary"]},
    {"keyword": "재결속", "description": "단절 후 다시 연결될 때 나는 무엇을 느끼는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_attachment"]},
    {"keyword": "감정이입", "description": "나는 상대의 감정을 어디까지 내 것으로 받아들이는가", "rel_tags": ["rel_lover", "rel_friend"], "psych_tags": ["psych_attachment", "psych_emotion"]},
    {"keyword": "존재감", "description": "내가 누군가에게 존재한다는 것을 어떻게 확인하는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_attachment", "psych_identity"]},
    {"keyword": "의지", "description": "나는 누구에게 기대고 있는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_attachment"]},
    {"keyword": "부재", "description": "상대가 없을 때 내 안에서 무엇이 움직이는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_attachment", "psych_emotion"]},
    {"keyword": "과보호", "description": "나는 보호라는 이름으로 상대를 통제하는가", "rel_tags": ["rel_family", "rel_lover"], "psych_tags": ["psych_attachment", "psych_boundary"]},
    {"keyword": "생이별", "description": "살아있지만 만나지 못하는 관계에서 나는 무엇을 느끼는가", "rel_tags": ["rel_family", "rel_lover"], "psych_tags": ["psych_attachment", "psych_emotion"]},
    {"keyword": "정서적 유대", "description": "감정으로만 연결된 관계는 얼마나 지속 가능한가", "rel_tags": ["rel_lover", "rel_friend"], "psych_tags": ["psych_attachment"]},
    {"keyword": "의존욕구", "description": "나는 의존하고 싶다는 욕구 자체를 어떻게 바라보는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_attachment", "psych_desire"]},
    {"keyword": "공동체감", "description": "나는 어디에 속해 있다는 느낌이 필요한가", "rel_tags": ["rel_society", "rel_friend"], "psych_tags": ["psych_attachment", "psych_identity"]},
    {"keyword": "애도", "description": "잃어버린 관계에 대해 나는 충분히 슬퍼했는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_attachment", "psych_trauma"]},
    {"keyword": "새벽감각", "description": "새벽에 유독 누군가가 그리워지는 이유는 무엇인가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_attachment", "psych_emotion"]},
    {"keyword": "이중성", "description": "가까워지고 싶으면서도 멀어지고 싶은 나는 누구인가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_attachment", "psych_identity"]},
    {"keyword": "어긋남", "description": "서로 다른 방향으로 향하는 두 사람을 어떻게 보는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_attachment", "psych_emotion"]},
    {"keyword": "혼재감정", "description": "사랑과 미움이 동시에 느껴질 때 나는 무엇을 하는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_attachment", "psych_emotion"]},
    {"keyword": "탈출충동", "description": "친밀한 관계에서 도망치고 싶을 때 그 감각은 무엇인가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_attachment", "psych_boundary"]},
    {"keyword": "첫 만남", "description": "처음 연결되는 순간 나는 무엇을 감지하는가", "rel_tags": ["rel_lover", "rel_friend"], "psych_tags": ["psych_attachment"]},
    {"keyword": "이름", "description": "상대가 내 이름을 부를 때 느껴지는 것은 무엇인가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_attachment", "psych_identity"]},
    {"keyword": "잔상", "description": "헤어진 뒤에도 남아있는 그 사람의 흔적은 무엇인가", "rel_tags": ["rel_lover"], "psych_tags": ["psych_attachment", "psych_trauma"]},

    # ── psych_emotion (60개) ──────────────────────────────────
    {"keyword": "슬픔", "description": "나는 슬픔을 어떤 방식으로 표현하거나 감추는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_emotion"]},
    {"keyword": "두려움", "description": "관계에서 내가 가장 두려워하는 것은 무엇인가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_emotion", "psych_trauma"]},
    {"keyword": "기쁨", "description": "나는 어떤 순간에 진심으로 기쁜가", "rel_tags": ["rel_self"], "psych_tags": ["psych_emotion"]},
    {"keyword": "당혹감", "description": "나를 당황스럽게 만드는 감정이나 상황은 무엇인가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_emotion"]},
    {"keyword": "허무", "description": "무언가를 얻었는데도 텅 빈 느낌이 드는 때는 언제인가", "rel_tags": ["rel_self"], "psych_tags": ["psych_emotion", "psych_identity"]},
    {"keyword": "억울함", "description": "나는 억울함을 어떻게 처리하는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_emotion"]},
    {"keyword": "설레임", "description": "설렘과 불안의 경계에서 나는 무엇을 느끼는가", "rel_tags": ["rel_lover"], "psych_tags": ["psych_emotion", "psych_desire"]},
    {"keyword": "짜증", "description": "나는 어떤 순간에 가장 짜증스러운가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_emotion"]},
    {"keyword": "무감각", "description": "감정이 마비될 때 나는 무엇을 하고 있는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_emotion", "psych_trauma"]},
    {"keyword": "질망", "description": "포기와 절망 사이 어딘가에서 나는 어떻게 버티는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_emotion"]},
    {"keyword": "놀람", "description": "예상치 못한 감정에 내가 반응하는 방식은 무엇인가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_emotion"]},
    {"keyword": "무기력", "description": "아무것도 하기 싫은 그 감각은 어디서 오는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_emotion", "psych_growth"]},
    {"keyword": "벅참", "description": "감당하기 어려울 만큼 커지는 감정을 나는 어떻게 다루는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_emotion"]},
    {"keyword": "흐뭇함", "description": "조용하게 만족스러운 그 순간은 언제인가", "rel_tags": ["rel_self", "rel_family"], "psych_tags": ["psych_emotion"]},
    {"keyword": "긴장", "description": "나는 관계에서 언제 가장 긴장하는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_emotion", "psych_attachment"]},
    {"keyword": "소외감", "description": "함께 있어도 혼자인 것 같은 느낌은 언제 오는가", "rel_tags": ["rel_self", "rel_society"], "psych_tags": ["psych_emotion", "psych_identity"]},
    {"keyword": "부러움", "description": "나는 무엇을 부러워하고 그 뒤에 무엇이 있는가", "rel_tags": ["rel_self", "rel_society"], "psych_tags": ["psych_emotion", "psych_identity"]},
    {"keyword": "원망", "description": "나는 누구를 원망하고 그것이 나에게 어떤 영향을 미치는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_emotion", "psych_trauma"]},
    {"keyword": "감동", "description": "나를 감동시키는 순간은 어떤 구조를 가지고 있는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_emotion"]},
    {"keyword": "편안함", "description": "나는 어떤 상태에서 진정한 편안함을 느끼는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_emotion", "psych_attachment"]},
    {"keyword": "미움", "description": "나는 누군가를 미워한다는 것을 어떻게 인정하는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_emotion"]},
    {"keyword": "연민", "description": "나는 연민과 동정심을 혼동하는가", "rel_tags": ["rel_self", "rel_society"], "psych_tags": ["psych_emotion"]},
    {"keyword": "기분", "description": "오늘 내 기분의 원인을 나는 알고 있는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_emotion"]},
    {"keyword": "정서", "description": "나의 감정적 기반은 어디에서 형성되었는가", "rel_tags": ["rel_self", "rel_family"], "psych_tags": ["psych_emotion", "psych_trauma"]},
    {"keyword": "감정조절", "description": "감정을 조절한다는 것이 억압과 어떻게 다른가", "rel_tags": ["rel_self"], "psych_tags": ["psych_emotion", "psych_growth"]},
    {"keyword": "눈물", "description": "나는 언제 울고 언제 울지 못하는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_emotion"]},
    {"keyword": "웃음", "description": "진심 어린 웃음과 가면 쓴 웃음은 어떻게 다른가", "rel_tags": ["rel_self", "rel_society"], "psych_tags": ["psych_emotion"]},
    {"keyword": "분개", "description": "불의를 마주할 때 내 감정은 어디를 향하는가", "rel_tags": ["rel_self", "rel_society"], "psych_tags": ["psych_emotion"]},
    {"keyword": "심드렁함", "description": "관심이 사라진다는 것은 관계에서 무엇을 의미하는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_emotion", "psych_attachment"]},
    {"keyword": "초조함", "description": "나는 어떤 상황에서 빨리 해결하려는 초조함을 느끼는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_emotion"]},
    {"keyword": "만족", "description": "나는 관계에서 무엇이 충족될 때 만족하는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_emotion", "psych_desire"]},
    {"keyword": "공허", "description": "무언가를 잃은 후의 공허는 어떻게 채워지는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_emotion", "psych_identity"]},
    {"keyword": "충격", "description": "감정적 충격이 내 몸에 어떻게 남는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_emotion", "psych_trauma"]},
    {"keyword": "안쓰러움", "description": "나는 상대를 안쓰럽게 볼 때 무엇을 하는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_emotion"]},
    {"keyword": "서운함", "description": "작은 서운함이 쌓이면 어떤 모습이 되는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_emotion", "psych_attachment"]},
    {"keyword": "걱정", "description": "나의 걱정은 사랑인가, 통제인가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_emotion", "psych_boundary"]},
    {"keyword": "감격", "description": "감격의 순간에 나는 어떤 사람이 되는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_emotion"]},
    {"keyword": "체념", "description": "체념과 수용은 어떻게 다른가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_emotion", "psych_growth"]},
    {"keyword": "활력", "description": "관계가 나에게 활력을 줄 때와 뺏을 때는 언제인가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_emotion", "psych_growth"]},
    {"keyword": "공포", "description": "관계에서 두려움이 공포가 되는 순간은 언제인가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_emotion", "psych_trauma"]},
    {"keyword": "혐오", "description": "나는 어떤 것에 혐오를 느끼며 그것은 나에 대해 무엇을 말하는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_emotion", "psych_identity"]},
    {"keyword": "희열", "description": "관계 안에서 극도의 기쁨을 느낀 순간은 언제인가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_emotion", "psych_desire"]},
    {"keyword": "상처", "description": "나는 상처를 어떻게 감지하고 어떻게 보호하는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_emotion", "psych_trauma"]},
    {"keyword": "해방감", "description": "관계에서 벗어날 때 느끼는 해방감은 무엇을 뜻하는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_emotion", "psych_identity"]},
    {"keyword": "평온", "description": "진정한 평온은 어떤 조건에서 오는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_emotion", "psych_growth"]},
    {"keyword": "울분", "description": "오래 쌓인 울분이 관계에서 어떻게 터지는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_emotion", "psych_trauma"]},
    {"keyword": "두근거림", "description": "두근거림이 기대인지 불안인지 구별할 수 있는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_emotion", "psych_desire"]},
    {"keyword": "냉담함", "description": "냉담함은 보호인가, 거절인가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_emotion", "psych_boundary"]},
    {"keyword": "감사결핍", "description": "감사를 표현하지 못하는 이유는 무엇인가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_emotion", "psych_boundary"]},
    {"keyword": "그늘", "description": "나에게 감정적으로 그늘진 부분은 어디인가", "rel_tags": ["rel_self"], "psych_tags": ["psych_emotion", "psych_trauma"]},
    {"keyword": "감정소진", "description": "나는 언제 감정적으로 완전히 소진되는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_emotion", "psych_growth"]},
    {"keyword": "혼란", "description": "내 감정이 뒤섞여 정리되지 않을 때 나는 어떻게 하는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_emotion", "psych_identity"]},
    {"keyword": "쑥스러움", "description": "나는 언제 쑥스러움을 느끼고 그것을 어떻게 처리하는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_emotion"]},
    {"keyword": "버거움", "description": "이 관계가 버거울 때 나는 무엇을 하는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_emotion", "psych_boundary"]},
    {"keyword": "쾌감", "description": "관계에서 쾌감을 느끼는 순간과 그 원인은 무엇인가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_emotion", "psych_desire"]},
    {"keyword": "몸감각", "description": "감정이 몸에 어떻게 나타나는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_emotion", "psych_sexuality"]},
    {"keyword": "감정언어", "description": "나는 내 감정에 이름 붙이는 것을 잘 하는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_emotion", "psych_boundary"]},
    {"keyword": "동요", "description": "어떤 말이나 상황이 나를 흔들어놓는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_emotion", "psych_attachment"]},
    {"keyword": "뿌듯함", "description": "나는 어떤 것을 이뤘을 때 진심으로 뿌듯한가", "rel_tags": ["rel_self"], "psych_tags": ["psych_emotion", "psych_growth"]},
    {"keyword": "아련함", "description": "지나간 것에 대한 아련함이 현재를 어떻게 물들이는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_emotion", "psych_attachment"]},
    {"keyword": "잔잔함", "description": "폭풍 같은 감정 없이 잔잔한 관계는 나에게 어떤 의미인가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_emotion"]},

    # ── psych_boundary (50개) ─────────────────────────────────
    {"keyword": "거절", "description": "나는 거절당하는 것과 거절하는 것 중 무엇이 더 어려운가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_boundary"]},
    {"keyword": "말하기", "description": "나는 어떤 말을 가장 꺼내기 어려운가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_boundary", "psych_emotion"]},
    {"keyword": "듣기", "description": "나는 상대의 말을 실제로 듣고 있는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_boundary"]},
    {"keyword": "표현", "description": "나는 감정을 어떤 방식으로 표현하는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_boundary", "psych_emotion"]},
    {"keyword": "반응", "description": "내가 보이는 즉각적 반응은 나의 어떤 면을 드러내는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_boundary"]},
    {"keyword": "무시", "description": "무시당한다고 느낄 때 나는 어떤 행동을 하는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_boundary", "psych_emotion"]},
    {"keyword": "넘어섬", "description": "상대가 내 경계를 넘었을 때 나는 어떻게 반응하는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_boundary"]},
    {"keyword": "맞춤", "description": "나는 상대에게 맞추는 게 자연스러운가, 아니면 지치는가", "rel_tags": ["rel_lover", "rel_friend"], "psych_tags": ["psych_boundary", "psych_identity"]},
    {"keyword": "양보", "description": "나는 양보를 선택으로 하는가, 두려움으로 하는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_boundary", "psych_identity"]},
    {"keyword": "주장", "description": "나는 내 의견을 어떤 방식으로 내세우는가", "rel_tags": ["rel_lover", "rel_society"], "psych_tags": ["psych_boundary", "psych_identity"]},
    {"keyword": "충고", "description": "나는 충고를 받을 때와 줄 때 어떤 감정을 느끼는가", "rel_tags": ["rel_lover", "rel_friend"], "psych_tags": ["psych_boundary"]},
    {"keyword": "지적", "description": "지적받는 것이 나에게 어떤 의미를 가지는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_boundary", "psych_identity"]},
    {"keyword": "동의압박", "description": "동의하지 않는데 동의하는 척할 때 나는 어떤 상태인가", "rel_tags": ["rel_lover", "rel_society"], "psych_tags": ["psych_boundary"]},
    {"keyword": "개입", "description": "나는 타인의 문제에 어디까지 개입하는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_boundary"]},
    {"keyword": "침묵경계", "description": "침묵으로 경계를 긋는 것은 얼마나 유효한가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_boundary"]},
    {"keyword": "투명성", "description": "나는 관계에서 얼마나 나를 드러내는가", "rel_tags": ["rel_lover", "rel_friend"], "psych_tags": ["psych_boundary", "psych_identity"]},
    {"keyword": "설명의무", "description": "나는 내 선택을 상대에게 설명해야 한다고 느끼는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_boundary", "psych_identity"]},
    {"keyword": "승인욕구", "description": "나는 상대의 승인 없이 스스로를 인정할 수 있는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_boundary", "psych_identity"]},
    {"keyword": "공간", "description": "나는 혼자만의 공간이 필요한가, 함께하는 공간이 필요한가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_boundary", "psych_attachment"]},
    {"keyword": "프라이버시", "description": "내가 지키고 싶은 개인 영역은 어디까지인가", "rel_tags": ["rel_lover", "rel_society"], "psych_tags": ["psych_boundary"]},
    {"keyword": "압력", "description": "나는 어떤 종류의 압력에 가장 쉽게 굴복하는가", "rel_tags": ["rel_lover", "rel_society"], "psych_tags": ["psych_boundary", "psych_identity"]},
    {"keyword": "눈치", "description": "나는 눈치를 보다가 무엇을 잃는가", "rel_tags": ["rel_lover", "rel_society"], "psych_tags": ["psych_boundary", "psych_identity"]},
    {"keyword": "해명", "description": "나는 왜 내가 하지 않은 일을 설명해야 한다고 느끼는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_boundary", "psych_emotion"]},
    {"keyword": "참음", "description": "나는 무엇을 참고 있는가, 그것은 지혜인가 회피인가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_boundary", "psych_emotion"]},
    {"keyword": "직접성", "description": "나는 원하는 것을 직접 말하는가, 돌려 말하는가", "rel_tags": ["rel_lover", "rel_friend"], "psych_tags": ["psych_boundary"]},
    {"keyword": "문자경계", "description": "메시지 한 통이 관계의 경계를 어떻게 드러내는가", "rel_tags": ["rel_lover", "rel_friend"], "psych_tags": ["psych_boundary"]},
    {"keyword": "부탁", "description": "나는 부탁하는 것이 어려운가, 부탁받는 것이 어려운가", "rel_tags": ["rel_lover", "rel_friend"], "psych_tags": ["psych_boundary"]},
    {"keyword": "호기심", "description": "나는 상대에 대해 어디까지 알고 싶은가", "rel_tags": ["rel_lover", "rel_friend"], "psych_tags": ["psych_boundary", "psych_attachment"]},
    {"keyword": "적당함", "description": "관계에서 적당함의 기준은 어디서 오는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_boundary"]},
    {"keyword": "이해요청", "description": "나는 상대에게 이해받기를 원하는가, 아니면 인정받기를 원하는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_boundary", "psych_identity"]},
    {"keyword": "말줄임", "description": "나는 어떤 말을 끝까지 하지 못하는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_boundary", "psych_emotion"]},
    {"keyword": "과잉해석", "description": "나는 상대의 말이나 행동을 과잉 해석하는 경향이 있는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_boundary", "psych_attachment"]},
    {"keyword": "단호함", "description": "나는 단호해야 할 때 단호한가", "rel_tags": ["rel_lover", "rel_society"], "psych_tags": ["psych_boundary", "psych_identity"]},
    {"keyword": "대화회피", "description": "나는 어떤 주제를 피하며 왜 그런가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_boundary", "psych_trauma"]},
    {"keyword": "모르는 척", "description": "알면서도 모르는 척하는 나는 무엇을 지키고 있는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_boundary"]},
    {"keyword": "명확함", "description": "나는 내 의사를 얼마나 명확히 전달하는가", "rel_tags": ["rel_lover", "rel_friend"], "psych_tags": ["psych_boundary"]},
    {"keyword": "간섭", "description": "나는 관심과 간섭을 어떻게 구분하는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_boundary"]},
    {"keyword": "전달방식", "description": "내가 감정을 전달하는 방식은 상대에게 어떻게 받아들여지는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_boundary", "psych_emotion"]},
    {"keyword": "과묵함", "description": "말이 없는 것이 나의 방어인가, 스타일인가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_boundary", "psych_identity"]},
    {"keyword": "이견", "description": "다른 의견을 가진 사람과 관계를 유지하는 방법은 무엇인가", "rel_tags": ["rel_lover", "rel_friend"], "psych_tags": ["psych_boundary", "psych_growth"]},
    {"keyword": "감정보고", "description": "나는 내 감정 상태를 상대에게 보고해야 한다고 느끼는가", "rel_tags": ["rel_lover"], "psych_tags": ["psych_boundary", "psych_identity"]},
    {"keyword": "자기표현", "description": "나는 나를 표현할 수 있는 공간을 충분히 갖고 있는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_boundary", "psych_identity"]},
    {"keyword": "수위조절", "description": "나는 감정의 강도를 어떻게 조절하는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_boundary", "psych_emotion"]},
    {"keyword": "감정전이", "description": "상대의 감정이 나에게 옮겨오는 것을 어떻게 막는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_boundary", "psych_emotion"]},
    {"keyword": "말의힘", "description": "나를 가장 크게 움직인 말은 무엇인가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_boundary", "psych_emotion"]},
    {"keyword": "핵심회피", "description": "대화에서 가장 중요한 것을 피해가는 나는 왜 그런가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_boundary", "psych_trauma"]},
    {"keyword": "관점차이", "description": "같은 상황을 전혀 다르게 보는 상대를 나는 어떻게 대하는가", "rel_tags": ["rel_lover", "rel_friend"], "psych_tags": ["psych_boundary", "psych_growth"]},
    {"keyword": "해석권", "description": "내 감정이나 행동을 해석할 권리는 누구에게 있는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_boundary", "psych_identity"]},
    {"keyword": "적극성", "description": "나는 원하는 것을 적극적으로 요청하는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_boundary", "psych_desire"]},
    {"keyword": "협상", "description": "관계에서 협상은 어떤 언어로 이루어지는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_boundary", "psych_growth"]},

    # ── psych_desire (50개) ───────────────────────────────────
    {"keyword": "원함", "description": "나는 관계에서 진심으로 원하는 것이 무엇인지 알고 있는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_desire"]},
    {"keyword": "필요", "description": "원하는 것과 필요한 것을 나는 구분하는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_desire"]},
    {"keyword": "갈망", "description": "나는 무엇을 간절히 원하며 그것이 두려운가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_desire"]},
    {"keyword": "쾌락", "description": "나에게 기쁨을 주는 것들에 나는 얼마나 솔직한가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_desire", "psych_sexuality"]},
    {"keyword": "탐색", "description": "나는 내 욕구를 탐색해본 경험이 있는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_desire", "psych_identity"]},
    {"keyword": "만족지연", "description": "나는 즉각적 만족과 깊은 만족 중 무엇을 더 원하는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_desire"]},
    {"keyword": "억압된 욕구", "description": "나는 어떤 욕구를 스스로 억누르고 있는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_desire", "psych_trauma"]},
    {"keyword": "자기욕구", "description": "나만을 위한 욕구를 갖는 것이 이기적인가", "rel_tags": ["rel_self"], "psych_tags": ["psych_desire", "psych_identity"]},
    {"keyword": "함께하고 싶음", "description": "특정 사람과 함께 있고 싶다는 욕구는 어디서 오는가", "rel_tags": ["rel_lover", "rel_friend"], "psych_tags": ["psych_desire", "psych_attachment"]},
    {"keyword": "에로스", "description": "나에게 에로틱한 에너지는 어떤 형태로 존재하는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_desire", "psych_sexuality"]},
    {"keyword": "자극", "description": "나는 무엇에 자극받을 때 살아있음을 느끼는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_desire"]},
    {"keyword": "충족", "description": "나는 어떤 방식으로 욕구가 충족될 때 온전한 만족을 느끼는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_desire"]},
    {"keyword": "수동성", "description": "욕구 표현에서 나는 얼마나 수동적인가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_desire", "psych_boundary"]},
    {"keyword": "판타지", "description": "나의 상상 속 이상적 관계는 현실과 어떻게 다른가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_desire", "psych_sexuality"]},
    {"keyword": "터치욕구", "description": "나는 신체적 접촉에 대한 욕구를 어떻게 표현하는가", "rel_tags": ["rel_lover"], "psych_tags": ["psych_desire", "psych_sexuality"]},
    {"keyword": "인정욕구", "description": "나는 칭찬과 인정이 없으면 어떻게 되는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_desire", "psych_identity"]},
    {"keyword": "소속욕구", "description": "어딘가에 속하고 싶다는 욕구가 나를 어디로 이끄는가", "rel_tags": ["rel_society", "rel_self"], "psych_tags": ["psych_desire", "psych_attachment"]},
    {"keyword": "성취욕", "description": "나는 관계에서도 성취를 추구하는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_desire", "psych_identity"]},
    {"keyword": "먹힘", "description": "상대에게 완전히 이해받고 싶다는 욕구는 현실적인가", "rel_tags": ["rel_lover"], "psych_tags": ["psych_desire", "psych_attachment"]},
    {"keyword": "새로움욕구", "description": "나는 관계에서 새로움을 얼마나 원하는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_desire"]},
    {"keyword": "돌봄욕구", "description": "돌봄받고 싶다는 욕구를 나는 어떻게 드러내는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_desire", "psych_attachment"]},
    {"keyword": "인격적 존중욕구", "description": "나는 인격체로 대우받고 싶다는 욕구를 표현하는가", "rel_tags": ["rel_lover", "rel_society"], "psych_tags": ["psych_desire", "psych_identity"]},
    {"keyword": "표현욕구", "description": "나는 내 감정을 표현해야 한다는 욕구를 느끼는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_desire", "psych_boundary"]},
    {"keyword": "사랑받고 싶음", "description": "나는 어떤 방식으로 사랑받기를 원하는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_desire", "psych_attachment"]},
    {"keyword": "욕구충돌", "description": "두 사람의 욕구가 충돌할 때 나는 어떻게 하는가", "rel_tags": ["rel_lover"], "psych_tags": ["psych_desire", "psych_boundary"]},
    {"keyword": "섹슈얼욕구", "description": "성적 욕구를 나는 얼마나 솔직하게 인정하는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_desire", "psych_sexuality"]},
    {"keyword": "평화욕구", "description": "나는 갈등을 피하고 싶은 욕구와 진실을 말하고 싶은 욕구 사이에서 어떻게 하는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_desire", "psych_boundary"]},
    {"keyword": "깊이", "description": "나는 관계의 깊이를 어떻게 측정하는가", "rel_tags": ["rel_lover", "rel_friend"], "psych_tags": ["psych_desire", "psych_attachment"]},
    {"keyword": "발견욕구", "description": "상대의 새로운 면을 발견할 때 나는 어떤 감정인가", "rel_tags": ["rel_lover", "rel_friend"], "psych_tags": ["psych_desire"]},
    {"keyword": "충동", "description": "나는 충동을 어떻게 다루는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_desire", "psych_boundary"]},
    {"keyword": "더 많이", "description": "관계에서 '더'를 원하는 나는 무엇이 부족한가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_desire", "psych_attachment"]},
    {"keyword": "감각욕구", "description": "나는 어떤 감각적 경험이 삶을 풍요롭게 하는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_desire", "psych_sexuality"]},
    {"keyword": "이상형", "description": "나의 이상형은 어디서 만들어졌는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_desire", "psych_attachment"]},
    {"keyword": "열정", "description": "나는 어떤 것에 진심으로 열정적인가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_desire", "psych_growth"]},
    {"keyword": "욕구인식", "description": "나는 내가 무엇을 원하는지 알아차리는 데 얼마나 걸리는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_desire"]},
    {"keyword": "애무", "description": "신체적 애정 표현에서 나는 무엇을 원하고 무엇이 어색한가", "rel_tags": ["rel_lover"], "psych_tags": ["psych_desire", "psych_sexuality"]},
    {"keyword": "특별함욕구", "description": "나는 상대에게 특별한 존재이고 싶은가", "rel_tags": ["rel_lover"], "psych_tags": ["psych_desire", "psych_identity"]},
    {"keyword": "나눔욕구", "description": "나는 내 것을 나누고 싶은 욕구가 강한가", "rel_tags": ["rel_lover", "rel_friend"], "psych_tags": ["psych_desire"]},
    {"keyword": "긴장감욕구", "description": "나는 관계에서 약간의 긴장감이 있어야 살아있는 느낌인가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_desire"]},
    {"keyword": "독립욕구", "description": "나는 관계 안에서도 독립적이고 싶은가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_desire", "psych_identity"]},
    {"keyword": "가까이 있음", "description": "물리적 가까움이 정서적 연결을 의미하는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_desire", "psych_attachment"]},
    {"keyword": "부드러움욕구", "description": "나는 관계에서 부드럽게 대해지고 싶은가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_desire", "psych_emotion"]},
    {"keyword": "공유욕구", "description": "나는 내 삶을 누군가와 공유하고 싶은가", "rel_tags": ["rel_lover", "rel_friend"], "psych_tags": ["psych_desire"]},
    {"keyword": "쾌락원칙", "description": "나는 즉각적 쾌락과 장기적 만족 중 무엇을 선택하는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_desire", "psych_growth"]},
    {"keyword": "비언어욕구", "description": "말이 아닌 다른 방식으로 사랑받고 싶은가", "rel_tags": ["rel_lover"], "psych_tags": ["psych_desire", "psych_sexuality"]},
    {"keyword": "성적자아", "description": "나는 나의 성적 자아를 어떻게 이해하고 있는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_desire", "psych_sexuality"]},
    {"keyword": "욕구거부감", "description": "어떤 욕구는 갖는 것 자체가 불편한가", "rel_tags": ["rel_self"], "psych_tags": ["psych_desire", "psych_trauma"]},
    {"keyword": "나를 원함", "description": "상대가 나를 원한다는 것을 느낄 때 나는 어떤가", "rel_tags": ["rel_lover"], "psych_tags": ["psych_desire", "psych_identity"]},
    {"keyword": "충분함", "description": "지금 이 관계가 충분한가, 아니면 더 필요한가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_desire"]},
    {"keyword": "결핍감", "description": "내 안에 채워지지 않는 것이 있다면 그것은 무엇인가", "rel_tags": ["rel_self"], "psych_tags": ["psych_desire", "psych_identity"]},

    # ── psych_identity (50개) ─────────────────────────────────
    {"keyword": "나다움", "description": "관계 안에서 나는 얼마나 나답게 있는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_identity"]},
    {"keyword": "가면", "description": "나는 어떤 모습을 숨기고 살아가는가", "rel_tags": ["rel_self", "rel_society"], "psych_tags": ["psych_identity"]},
    {"keyword": "페르소나", "description": "사회적 나와 진짜 나의 거리는 얼마나 되는가", "rel_tags": ["rel_self", "rel_society"], "psych_tags": ["psych_identity"]},
    {"keyword": "자아상", "description": "나는 내 자신을 어떻게 바라보는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_identity"]},
    {"keyword": "핵심가치", "description": "내가 절대 타협하지 않는 가치는 무엇인가", "rel_tags": ["rel_self", "rel_society"], "psych_tags": ["psych_identity"]},
    {"keyword": "자기혐오", "description": "나는 언제 자신을 싫어하는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_identity", "psych_trauma"]},
    {"keyword": "자기사랑", "description": "나는 나 자신을 사랑하는 방법을 알고 있는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_identity", "psych_growth"]},
    {"keyword": "내면아이", "description": "내 안의 어린 나는 무엇을 원하는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_identity", "psych_trauma"]},
    {"keyword": "자기신뢰", "description": "나는 내 감각과 판단을 믿는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_identity"]},
    {"keyword": "진정성", "description": "나는 얼마나 진정성 있게 살고 있는가", "rel_tags": ["rel_self", "rel_society"], "psych_tags": ["psych_identity"]},
    {"keyword": "타인시선", "description": "타인이 나를 어떻게 볼까가 내 행동을 얼마나 결정하는가", "rel_tags": ["rel_self", "rel_society"], "psych_tags": ["psych_identity"]},
    {"keyword": "자기결정", "description": "나는 내 삶의 결정을 스스로 내리는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_identity", "psych_boundary"]},
    {"keyword": "원칙", "description": "나는 어떤 원칙을 가지고 관계에 임하는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_identity", "psych_boundary"]},
    {"keyword": "자기비판", "description": "나는 나 자신에게 어떤 말을 가장 많이 하는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_identity", "psych_emotion"]},
    {"keyword": "배경", "description": "내가 어떤 환경에서 자랐는지가 지금의 나를 어떻게 설명하는가", "rel_tags": ["rel_self", "rel_family"], "psych_tags": ["psych_identity", "psych_trauma"]},
    {"keyword": "정체성 혼란", "description": "나는 어떤 상황에서 내가 누구인지 모르겠는 느낌인가", "rel_tags": ["rel_self"], "psych_tags": ["psych_identity"]},
    {"keyword": "사회적 역할", "description": "사회가 기대하는 역할과 내가 원하는 역할은 같은가", "rel_tags": ["rel_self", "rel_society"], "psych_tags": ["psych_identity"]},
    {"keyword": "민족정체성", "description": "나는 어떤 문화적 정체성을 가지고 있는가", "rel_tags": ["rel_self", "rel_society"], "psych_tags": ["psych_identity"]},
    {"keyword": "직업정체성", "description": "직업이 나를 정의하는가, 아니면 나의 일부인가", "rel_tags": ["rel_self", "rel_society"], "psych_tags": ["psych_identity"]},
    {"keyword": "경쟁심", "description": "나는 왜 누군가와 비교하며 자신을 평가하는가", "rel_tags": ["rel_self", "rel_society"], "psych_tags": ["psych_identity", "psych_emotion"]},
    {"keyword": "자기표상", "description": "내가 만들어온 나의 이미지는 진짜 나인가", "rel_tags": ["rel_self"], "psych_tags": ["psych_identity"]},
    {"keyword": "독특함", "description": "나는 나만의 것이 있다고 느끼는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_identity"]},
    {"keyword": "공감능력", "description": "나는 공감 능력이 있는 사람인가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_identity", "psych_emotion"]},
    {"keyword": "잠재력", "description": "나는 아직 발견하지 못한 나의 잠재력을 믿는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_identity", "psych_growth"]},
    {"keyword": "자기개념", "description": "나는 어떤 사람이라는 스스로의 이야기를 갖고 있는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_identity"]},
    {"keyword": "자기소개", "description": "나를 한 문장으로 소개한다면 어떻게 말하겠는가", "rel_tags": ["rel_self", "rel_society"], "psych_tags": ["psych_identity"]},
    {"keyword": "나이듦", "description": "나이가 들면서 나는 어떻게 변하고 있는가", "rel_tags": ["rel_self", "rel_society"], "psych_tags": ["psych_identity", "psych_growth"]},
    {"keyword": "몸정체성", "description": "내 몸은 나를 어떻게 표현하는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_identity", "psych_sexuality"]},
    {"keyword": "개인사", "description": "내 개인 역사에서 지금의 나를 만든 사건은 무엇인가", "rel_tags": ["rel_self", "rel_family"], "psych_tags": ["psych_identity", "psych_trauma"]},
    {"keyword": "자기수용", "description": "나는 내 단점을 어떻게 받아들이는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_identity", "psych_growth"]},
    {"keyword": "경계정체성", "description": "내가 가진 경계는 나를 보호하는가 가두는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_identity", "psych_boundary"]},
    {"keyword": "목적의식", "description": "나는 왜 살고 있는가, 그 답을 찾았는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_identity", "psych_growth"]},
    {"keyword": "자기충분", "description": "나는 혼자서도 충분한 존재라고 느끼는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_identity"]},
    {"keyword": "자기책임", "description": "나는 내 삶과 감정에 얼마나 책임을 지는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_identity", "psych_growth"]},
    {"keyword": "내면갈등", "description": "나의 두 가지 모습이 충돌할 때 어떻게 하는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_identity"]},
    {"keyword": "자기연민", "description": "나는 나 자신에게 연민을 가지는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_identity", "psych_emotion"]},
    {"keyword": "기억속의나", "description": "과거의 나는 현재의 나와 얼마나 다른가", "rel_tags": ["rel_self"], "psych_tags": ["psych_identity", "psych_trauma"]},
    {"keyword": "자아탐색", "description": "나는 나를 알아가는 과정을 즐기는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_identity", "psych_growth"]},
    {"keyword": "존재이유", "description": "나는 어떤 관계에서 내 존재가 의미 있다고 느끼는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_identity"]},
    {"keyword": "자기주도", "description": "나는 내 삶의 방향을 스스로 결정하는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_identity", "psych_growth"]},
    {"keyword": "분화", "description": "나는 가족이나 파트너로부터 충분히 분화되어 있는가", "rel_tags": ["rel_self", "rel_family"], "psych_tags": ["psych_identity", "psych_attachment"]},
    {"keyword": "중심", "description": "흔들릴 때 나는 어디로 돌아가는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_identity"]},
    {"keyword": "취향", "description": "나만의 취향이 나를 어떻게 정의하는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_identity"]},
    {"keyword": "세계관", "description": "나의 세계를 바라보는 방식은 어디서 만들어졌는가", "rel_tags": ["rel_self", "rel_society"], "psych_tags": ["psych_identity"]},
    {"keyword": "자아발달", "description": "나는 어느 지점에서 멈추어 있는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_identity", "psych_growth"]},
    {"keyword": "복잡성", "description": "나는 내 복잡함을 인정하는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_identity"]},
    {"keyword": "양면성", "description": "나의 상반되는 두 면을 어떻게 품고 있는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_identity"]},
    {"keyword": "경계설정", "description": "내가 설정한 경계는 진짜 나의 것인가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_identity", "psych_boundary"]},
    {"keyword": "나의언어", "description": "나는 어떤 언어로 세상과 소통하는가", "rel_tags": ["rel_self", "rel_society"], "psych_tags": ["psych_identity", "psych_boundary"]},
    {"keyword": "자기지각", "description": "지금 이 순간 나는 나 자신을 어떻게 느끼는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_identity"]},

    # ── psych_trauma (40개) ───────────────────────────────────
    {"keyword": "각인", "description": "어떤 경험이 내 관계 방식에 깊이 새겨져 있는가", "rel_tags": ["rel_self", "rel_family"], "psych_tags": ["psych_trauma"]},
    {"keyword": "반복패턴", "description": "나는 같은 종류의 관계를 반복하는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_trauma"]},
    {"keyword": "과거 영향", "description": "과거의 어떤 경험이 오늘의 나를 지배하는가", "rel_tags": ["rel_self", "rel_family"], "psych_tags": ["psych_trauma"]},
    {"keyword": "방어기제", "description": "나는 어떤 방어기제를 주로 사용하는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_trauma"]},
    {"keyword": "촉발점", "description": "무엇이 내 오래된 상처를 건드리는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_trauma"]},
    {"keyword": "회복력", "description": "나는 힘든 경험에서 어떻게 다시 일어서는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_trauma", "psych_growth"]},
    {"keyword": "묻힌 기억", "description": "기억하고 싶지 않지만 계속 나타나는 것은 무엇인가", "rel_tags": ["rel_self", "rel_family"], "psych_tags": ["psych_trauma"]},
    {"keyword": "해리", "description": "나는 극심한 스트레스 상황에서 어떻게 반응하는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_trauma"]},
    {"keyword": "생존전략", "description": "어린 시절 내가 살아남기 위해 만든 방식은 무엇인가", "rel_tags": ["rel_self", "rel_family"], "psych_tags": ["psych_trauma"]},
    {"keyword": "상처의근원", "description": "가장 오래된 상처는 어디서 왔는가", "rel_tags": ["rel_self", "rel_family"], "psych_tags": ["psych_trauma"]},
    {"keyword": "과잉경계", "description": "나는 상처받지 않으려고 너무 많은 것을 차단하는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_trauma", "psych_boundary"]},
    {"keyword": "감정억압", "description": "나는 어떤 감정을 절대 느끼지 않으려 하는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_trauma", "psych_emotion"]},
    {"keyword": "가해와피해", "description": "나는 관계에서 언제 가해자이고 피해자인가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_trauma"]},
    {"keyword": "망각", "description": "잊고 싶은 것을 잊는 것이 치유인가", "rel_tags": ["rel_self"], "psych_tags": ["psych_trauma", "psych_growth"]},
    {"keyword": "자기보호", "description": "나는 나를 지키기 위해 무엇을 하는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_trauma", "psych_boundary"]},
    {"keyword": "반복강박", "description": "알면서도 반복되는 그 행동의 원인은 무엇인가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_trauma"]},
    {"keyword": "과각성", "description": "나는 작은 신호에도 과도하게 긴장하는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_trauma"]},
    {"keyword": "얼어붙음", "description": "위협을 느낄 때 나는 얼어붙는가 싸우는가 도망치는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_trauma"]},
    {"keyword": "신체기억", "description": "트라우마가 몸에 어떻게 저장되어 있는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_trauma", "psych_sexuality"]},
    {"keyword": "수용", "description": "과거를 수용한다는 것은 무엇을 의미하는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_trauma", "psych_growth"]},
    {"keyword": "전이", "description": "나는 상대에게 과거 사람의 모습을 투영하는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_trauma"]},
    {"keyword": "통증기억", "description": "감정적 통증이 신체적 통증처럼 남는 경험이 있는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_trauma"]},
    {"keyword": "치료경험", "description": "나는 심리적 도움을 받은 경험이 있는가, 그것이 도움이 됐는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_trauma", "psych_growth"]},
    {"keyword": "안전지대", "description": "나에게 심리적 안전지대는 어디인가", "rel_tags": ["rel_self"], "psych_tags": ["psych_trauma", "psych_attachment"]},
    {"keyword": "재경험", "description": "과거 상황이 현재에서 재현될 때 나는 어떻게 반응하는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_trauma"]},
    {"keyword": "죄의식", "description": "내 탓이 아닌데 내 탓이라고 느끼는 순간은 언제인가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_trauma", "psych_emotion"]},
    {"keyword": "경보반응", "description": "내 몸의 경보 반응이 과거와 연결되어 있는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_trauma"]},
    {"keyword": "내면비판자", "description": "나를 가장 심하게 비난하는 목소리는 어디서 왔는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_trauma", "psych_identity"]},
    {"keyword": "과거청산", "description": "나는 과거와 어떻게 관계를 정리하고 있는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_trauma", "psych_growth"]},
    {"keyword": "세대전달", "description": "부모에게 받은 것 중 내가 다음에 전달하고 싶지 않은 것은", "rel_tags": ["rel_family", "rel_self"], "psych_tags": ["psych_trauma"]},
    {"keyword": "상처자각", "description": "나는 내가 상처받았다는 것을 인정하는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_trauma"]},
    {"keyword": "용기있는기억", "description": "떠올리기 용기가 필요한 기억은 무엇인가", "rel_tags": ["rel_self"], "psych_tags": ["psych_trauma", "psych_growth"]},
    {"keyword": "회복과정", "description": "나는 현재 어떤 회복의 과정에 있는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_trauma", "psych_growth"]},
    {"keyword": "연결된 상처", "description": "이 감정이 과거의 어느 순간과 연결되어 있는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_trauma"]},
    {"keyword": "과거의 나에게", "description": "과거의 나에게 지금 무슨 말을 해주고 싶은가", "rel_tags": ["rel_self"], "psych_tags": ["psych_trauma", "psych_growth"]},
    {"keyword": "두려운 반복", "description": "다시는 겪고 싶지 않은 상황이 다가올 때 나는 어떻게 하는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_trauma"]},
    {"keyword": "침잠", "description": "슬픔이나 두려움에 가라앉을 때 나는 거기 얼마나 머무는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_trauma", "psych_emotion"]},
    {"keyword": "분리된나", "description": "감정적으로 분리된 채 사는 것이 편한가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_trauma", "psych_identity"]},
    {"keyword": "낙인", "description": "내가 스스로에게 붙인 낙인은 무엇인가", "rel_tags": ["rel_self"], "psych_tags": ["psych_trauma", "psych_identity"]},
    {"keyword": "희망", "description": "상처에도 불구하고 나는 무엇에 희망을 두는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_trauma", "psych_growth"]},

    # ── psych_growth (40개) ───────────────────────────────────
    {"keyword": "배움", "description": "나는 관계에서 무엇을 배우고 있는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_growth"]},
    {"keyword": "시작", "description": "새로운 시작이 두려운 이유는 무엇인가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_growth"]},
    {"keyword": "실패", "description": "나는 실패를 어떻게 받아들이는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_growth", "psych_identity"]},
    {"keyword": "성찰", "description": "나는 나 자신을 얼마나 자주 돌아보는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_growth"]},
    {"keyword": "도전", "description": "나는 어떤 도전을 앞에 두고 있는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_growth"]},
    {"keyword": "전환점", "description": "내 삶의 전환점은 어떤 경험에서 왔는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_growth"]},
    {"keyword": "인내", "description": "나는 무엇을 견디고 있으며 그것이 성장인가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_growth"]},
    {"keyword": "유연성", "description": "나는 얼마나 유연하게 변화를 받아들이는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_growth"]},
    {"keyword": "자기돌봄", "description": "나는 스스로를 어떻게 돌보고 있는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_growth", "psych_identity"]},
    {"keyword": "경청", "description": "나는 상대를 깊이 듣는 능력을 키우고 있는가", "rel_tags": ["rel_lover", "rel_friend"], "psych_tags": ["psych_growth", "psych_boundary"]},
    {"keyword": "모범", "description": "나는 어떤 삶의 모범을 따르고 있는가", "rel_tags": ["rel_self", "rel_family"], "psych_tags": ["psych_growth"]},
    {"keyword": "확장", "description": "관계가 내 세계를 어떻게 넓혀주는가", "rel_tags": ["rel_lover", "rel_friend"], "psych_tags": ["psych_growth"]},
    {"keyword": "반면교사", "description": "이 경험에서 내가 배우지 않으려는 것은 무엇인가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_growth"]},
    {"keyword": "통합", "description": "내 경험들을 하나의 이야기로 통합하는 과정에 있는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_growth", "psych_identity"]},
    {"keyword": "용기있는대화", "description": "나는 어렵지만 필요한 대화를 시작하는가", "rel_tags": ["rel_lover", "rel_family"], "psych_tags": ["psych_growth", "psych_boundary"]},
    {"keyword": "버리기", "description": "더 이상 나에게 맞지 않는 것을 내려놓을 수 있는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_growth"]},
    {"keyword": "자기개발", "description": "나는 어떤 방식으로 스스로를 발전시키는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_growth"]},
    {"keyword": "과정", "description": "결과보다 과정에 집중할 수 있는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_growth"]},
    {"keyword": "고마운 경험", "description": "힘들었지만 지금은 감사한 경험이 있는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_growth"]},
    {"keyword": "재정의", "description": "나는 관계나 사랑을 어떻게 새롭게 정의하고 있는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_growth", "psych_identity"]},
    {"keyword": "성숙", "description": "나는 어떤 면에서 이전보다 성숙해졌는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_growth"]},
    {"keyword": "방향", "description": "지금 내가 향하고 있는 방향은 어디인가", "rel_tags": ["rel_self"], "psych_tags": ["psych_growth", "psych_identity"]},
    {"keyword": "낯선나", "description": "내가 몰랐던 내 모습을 발견한 경험은", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_growth", "psych_identity"]},
    {"keyword": "속도", "description": "나는 성장의 속도에 만족하는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_growth"]},
    {"keyword": "혼돈속성장", "description": "혼란스러운 시기가 나를 어떻게 성장시켰는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_growth"]},
    {"keyword": "멘토", "description": "나는 누구에게서 배우고 있는가", "rel_tags": ["rel_self", "rel_society"], "psych_tags": ["psych_growth"]},
    {"keyword": "가능성", "description": "나는 내 안의 가능성을 얼마나 믿는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_growth", "psych_identity"]},
    {"keyword": "한계수용", "description": "나는 내 한계를 어떻게 받아들이는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_growth", "psych_identity"]},
    {"keyword": "호기심어린삶", "description": "나는 삶에 대한 호기심을 유지하고 있는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_growth"]},
    {"keyword": "습관변화", "description": "나는 어떤 습관을 바꾸려 하고 있는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_growth"]},
    {"keyword": "자기관찰", "description": "나는 내 행동 패턴을 알아차리는 연습을 하는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_growth"]},
    {"keyword": "지금여기", "description": "나는 지금 이 순간에 충분히 있는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_growth"]},
    {"keyword": "관계성장", "description": "이 관계가 나를 더 나은 사람으로 만드는가", "rel_tags": ["rel_lover", "rel_friend"], "psych_tags": ["psych_growth"]},
    {"keyword": "직면", "description": "나는 외면해온 것과 어떻게 마주하는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_growth", "psych_trauma"]},
    {"keyword": "선물", "description": "이 관계 혹은 경험이 나에게 준 선물은 무엇인가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_growth"]},
    {"keyword": "씨앗", "description": "지금 내 안에서 자라고 있는 것은 무엇인가", "rel_tags": ["rel_self"], "psych_tags": ["psych_growth"]},
    {"keyword": "온전함", "description": "나는 언제 가장 온전한 나인가", "rel_tags": ["rel_self"], "psych_tags": ["psych_growth", "psych_identity"]},
    {"keyword": "자기약속", "description": "나는 나 자신과 한 약속을 지키고 있는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_growth"]},
    {"keyword": "고요함", "description": "고요함 속에서 나는 무엇을 발견하는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_growth", "psych_emotion"]},
    {"keyword": "다음단계", "description": "이 관계에서 내가 성장하기 위한 다음 단계는 무엇인가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_growth"]},

    # ── psych_sexuality (40개) ───────────────────────────────
    {"keyword": "성적자각", "description": "나는 언제 처음으로 내 성적 감각을 인식했는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_sexuality"]},
    {"keyword": "몸 긍정", "description": "나는 내 몸을 긍정하는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_sexuality", "psych_identity"]},
    {"keyword": "성적소통", "description": "나는 성적 욕구와 경계를 상대에게 어떻게 전달하는가", "rel_tags": ["rel_lover"], "psych_tags": ["psych_sexuality", "psych_boundary"]},
    {"keyword": "성교육", "description": "나는 어디서 성에 대한 지식을 얻었으며 그것은 올바른 것이었나", "rel_tags": ["rel_self", "rel_society"], "psych_tags": ["psych_sexuality"]},
    {"keyword": "성적수치심", "description": "나는 성적인 욕구나 행동에 대해 수치심을 느끼는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_sexuality", "psych_trauma"]},
    {"keyword": "오르가슴", "description": "나는 오르가슴에 대해 어떤 인식과 경험을 가지고 있는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_sexuality"]},
    {"keyword": "자위", "description": "자위는 나에게 어떤 의미인가", "rel_tags": ["rel_self"], "psych_tags": ["psych_sexuality"]},
    {"keyword": "성적거부감", "description": "어떤 성적 상황이나 요청이 나를 불편하게 하는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_sexuality", "psych_boundary"]},
    {"keyword": "성적선호", "description": "나는 어떤 성적 경험을 좋아하고 어떤 것이 맞지 않는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_sexuality"]},
    {"keyword": "성과 사랑", "description": "나에게 섹스와 사랑은 분리되는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_sexuality", "psych_attachment"]},
    {"keyword": "성적환상", "description": "내가 상상하는 성적 장면이 나에게 무엇을 말해주는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_sexuality", "psych_desire"]},
    {"keyword": "성적자신감", "description": "나는 성적 관계에서 자신감이 있는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_sexuality"]},
    {"keyword": "몸 경계", "description": "내 몸에서 만져지고 싶지 않은 부분이 있는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_sexuality", "psych_boundary"]},
    {"keyword": "성적 대화", "description": "나는 성에 관한 대화를 파트너와 편하게 나눌 수 있는가", "rel_tags": ["rel_lover"], "psych_tags": ["psych_sexuality", "psych_boundary"]},
    {"keyword": "성욕변화", "description": "내 성욕은 상황, 감정, 시간에 따라 어떻게 변하는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_sexuality"]},
    {"keyword": "친밀성장벽", "description": "신체적 친밀감을 방해하는 내 안의 것은 무엇인가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_sexuality", "psych_trauma"]},
    {"keyword": "상호동의", "description": "나는 성적 상황에서 동의를 어떻게 확인하는가", "rel_tags": ["rel_lover"], "psych_tags": ["psych_sexuality", "psych_boundary"]},
    {"keyword": "몸언어", "description": "내 몸은 어떤 방식으로 감정과 욕구를 표현하는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_sexuality", "psych_emotion"]},
    {"keyword": "쾌감 지도", "description": "나는 내 몸의 쾌감 지도를 알고 있는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_sexuality"]},
    {"keyword": "성적트라우마", "description": "성적 트라우마가 현재 나의 관계에 영향을 미치는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_sexuality", "psych_trauma"]},
    {"keyword": "성 긍정", "description": "나는 성을 긍정적이고 건강한 것으로 바라보는가", "rel_tags": ["rel_self", "rel_society"], "psych_tags": ["psych_sexuality"]},
    {"keyword": "성적 커뮤니케이션", "description": "나는 원하는 것과 원하지 않는 것을 성적 관계에서 말할 수 있는가", "rel_tags": ["rel_lover"], "psych_tags": ["psych_sexuality", "psych_boundary"]},
    {"keyword": "성별 기대", "description": "사회가 내 성별에 기대하는 성적 역할에 나는 어떻게 반응하는가", "rel_tags": ["rel_self", "rel_society"], "psych_tags": ["psych_sexuality", "psych_identity"]},
    {"keyword": "성적 회복력", "description": "성적으로 불쾌하거나 상처받은 경험에서 어떻게 회복했는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_sexuality", "psych_trauma"]},
    {"keyword": "몸과마음", "description": "섹스할 때 내 몸과 마음은 같은 곳에 있는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_sexuality"]},
    {"keyword": "성적 다양성", "description": "나는 다양한 성적 지향과 표현에 대해 어떻게 생각하는가", "rel_tags": ["rel_self", "rel_society"], "psych_tags": ["psych_sexuality", "psych_identity"]},
    {"keyword": "친밀한 취약함", "description": "성적으로 취약해지는 것이 나에게 어떤 의미인가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_sexuality", "psych_attachment"]},
    {"keyword": "욕구 말하기", "description": "성적 욕구를 직접 말하는 것이 어려운가", "rel_tags": ["rel_lover"], "psych_tags": ["psych_sexuality", "psych_boundary"]},
    {"keyword": "억압된 성", "description": "사회나 가정에서 억압된 성 인식이 나에게 남아있는가", "rel_tags": ["rel_self", "rel_society"], "psych_tags": ["psych_sexuality", "psych_trauma"]},
    {"keyword": "성과 자존감", "description": "성적 경험이 나의 자존감에 어떤 영향을 미치는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_sexuality", "psych_identity"]},
    {"keyword": "성적 규범", "description": "내가 따르는 성적 규범은 누가 만든 것인가", "rel_tags": ["rel_self", "rel_society"], "psych_tags": ["psych_sexuality", "psych_identity"]},
    {"keyword": "충분한 쾌감", "description": "나는 충분한 쾌감을 받고 있는가, 그것을 요청하는가", "rel_tags": ["rel_lover", "rel_self"], "psych_tags": ["psych_sexuality", "psych_desire"]},
    {"keyword": "성적 자율성", "description": "내 몸과 성에 대한 결정권은 온전히 나에게 있는가", "rel_tags": ["rel_self", "rel_lover"], "psych_tags": ["psych_sexuality", "psych_identity"]},
    {"keyword": "비성적 친밀감", "description": "섹스 없이 신체적으로 친밀한 것이 나에게 충분한가", "rel_tags": ["rel_lover"], "psych_tags": ["psych_sexuality", "psych_attachment"]},
    {"keyword": "성경험 이야기", "description": "나는 내 성 경험을 어떻게 이야기하는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_sexuality", "psych_identity"]},
    {"keyword": "성적 해방", "description": "나는 성적으로 자유롭다고 느끼는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_sexuality", "psych_identity"]},
    {"keyword": "성욕일치", "description": "파트너와 성욕의 방향이 다를 때 어떻게 하는가", "rel_tags": ["rel_lover"], "psych_tags": ["psych_sexuality", "psych_boundary"]},
    {"keyword": "몸 탐색", "description": "나는 내 몸을 얼마나 탐색하고 이해하고 있는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_sexuality"]},
    {"keyword": "성적 호기심", "description": "내 성적 호기심을 나는 어떻게 다루는가", "rel_tags": ["rel_self"], "psych_tags": ["psych_sexuality", "psych_desire"]},
    {"keyword": "성과 관계", "description": "섹스가 관계에서 어떤 역할을 하는가", "rel_tags": ["rel_lover"], "psych_tags": ["psych_sexuality", "psych_attachment"]},
]

# ──────────────────────────────────────────────────────────────
# 실행
# ──────────────────────────────────────────────────────────────
def main():
    print("=== Step 2: 기존 키워드 태그 배정 ===")
    existing = sb_get_all()
    id_map = {row["keyword"]: row["id"] for row in existing}

    patched = 0
    for kw, (rel_tags, psych_tags) in EXISTING_TAGS.items():
        kw_id = id_map.get(kw)
        if kw_id:
            sb_patch(kw_id, rel_tags, psych_tags)
            patched += 1
            print(f"  PATCH: {kw}")
        else:
            print(f"  [WARN] 키워드 없음: {kw}")
    print(f"Step 2 완료: {patched}개 패치\n")

    print("=== Step 3: 신규 키워드 삽입 ===")
    existing_keywords = {row["keyword"] for row in existing}
    to_insert = [k for k in NEW_KEYWORDS if k["keyword"] not in existing_keywords]
    print(f"  삽입 대상: {len(to_insert)}개 (중복 제외)")

    # 배치 단위로 삽입 (Supabase 250개 limit 고려)
    batch_size = 50
    inserted = 0
    for i in range(0, len(to_insert), batch_size):
        batch = to_insert[i:i+batch_size]
        sb_insert_batch(batch)
        inserted += len(batch)
        print(f"  삽입 완료: {inserted}/{len(to_insert)}")
        time.sleep(0.3)

    print(f"\nStep 3 완료: {inserted}개 삽입")

    # 분포 확인
    print("\n=== 카테고리별 분포 확인 ===")
    all_kw = sb_get_all()
    print(f"  총 키워드: {len(all_kw)}개")

if __name__ == "__main__":
    main()
